groups:
  - name: example
    rules:
      - alert: HighCPU
        expr: process_cpu_seconds_total > 0.5
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
